default_platform(:ios)

platform :ios do
  desc "Release build and upload to App Store Connect"
  lane :release do

    # 1. CI 환경 설정
    setup_ci

    # 2. App Store Connect API 연결
    app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_KEY_CONTENT"],
      is_key_content_base64: true
    )

    # 3. 배포용 인증서 및 프로파일 동기화
    match(
      type: "appstore",
      readonly: true
    )

    # 4. 앱 빌드 및 아카이브
    build_app(
      scheme: "Neki-iOS",
      configuration: "Release",
      export_method: "app-store"
    )

    # 5. TestFlight 업로드
    upload_to_app_store(
      skip_metadata: true,
      skip_screenshots: true,
      submit_for_review: false,
      run_precheck_before_submit: false
    )
  end
end