name: iOS Release CI

on:
  push:
    branches:
      - release

# 최신 push에 관한 CI 작업만 수행
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app

      - name: Install Ruby Gems
        run: bundle install

      - name: Run Fastlane Release
        run: bundle exec fastlane release
        env:
          APP_IDENTIFIER_RELEASE: ${{ secrets.APP_IDENTIFIER }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          TEAM_ID: ${{ secrets.TEAM_ID }}
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          ASC_KEY_CONTENT: ${{ secrets.ASC_KEY_CONTENT }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
